# Generated by Django 3.2.23 on 2024-02-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='texto',
            field=models.CharField(max_length=300),
        ),
    ]
