# Generated by Django 3.2.23 on 2024-03-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0002_alter_resposta_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='texto',
            field=models.CharField(max_length=500),
        ),
    ]
