# Generated by Django 3.2.23 on 2024-03-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0003_auto_20240314_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='texto',
            field=models.CharField(max_length=800),
        ),
    ]
