# Generated by Django 3.2.23 on 2024-03-21 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provas', '0004_alter_resposta_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provas.prova')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provas.pergunta')),
                ('respostas', models.ManyToManyField(to='provas.Resposta')),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provas.tentativa')),
            ],
        ),
    ]
