# Generated by Django 3.2.23 on 2025-07-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0005_respostausuario_tentativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativa',
            name='prova',
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='RespostaUsuario',
        ),
        migrations.DeleteModel(
            name='Tentativa',
        ),
    ]
